# Generated by Django 3.1.5 on 2021-01-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('balance', models.FloatField()),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_dollars', models.FloatField()),
                ('payment_period_in_days', models.PositiveIntegerField()),
                ('annual_percentage_interest_rate', models.FloatField()),
                ('status', models.CharField(choices=[('FD', 'Funded'), ('CD', 'Completed'), ('IL', 'Idle')], default='IL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_dollars', models.FloatField()),
                ('payment_period_in_days', models.PositiveIntegerField()),
            ],
        ),
    ]
