# Generated by Django 3.1.5 on 2021-01-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.borrower'),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='investor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.investor'),
        ),
    ]
