# Generated by Django 3.1.5 on 2021-01-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210128_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
