# Generated by Django 3.1.5 on 2021-01-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210128_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.investor'),
        ),
        migrations.AlterField(
            model_name='loanoffer',
            name='investor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.investor'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='scheduled_payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.scheduledpayment'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.borrower'),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.loan'),
        ),
    ]
