# Generated by Django 3.1.5 on 2021-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210128_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpayment',
            old_name='amount',
            new_name='amount_in_dollars',
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='amount_in_dollars',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
