# Generated by Django 3.1.5 on 2021-01-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210128_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('FD', 'Funded'), ('CD', 'Completed')], max_length=2),
        ),
    ]
